- name: Download Minikube binary
  get_url:
    url: https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64/
    dest: /usr/local/bin/minikube
    mode: '0755'

- name: Install required packages for Minikube
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - conntrack
    - ebtables
    - iptables
    - socat
    - arptables
    - libvirt-clients
    - libvirt-daemon-system
    - qemu-kvm

- name: Add Minikube to PATH
  lineinfile:
    path: /etc/profile
    line: 'export PATH=$PATH:/usr/local/bin'
    state: present



- name: Ensure Minikube is installed
  command: /usr/local/bin/minikube version
  register: minikube_version
  changed_when: false
  failed_when: minikube_version.rc != 0

- name: start minikube
  command: minikube start --driver=docker
  