---
- name: Update package index
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create directory for keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.gpg
    mode: '0644'

- name: Add Docker repository
  copy:
    content: |
      deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    dest: /etc/apt/sources.list.d/docker.list

- name: Update package index after adding Docker repository
  apt:
    update_cache: yes
- name: Create Docker group
  command: groupadd docker
  ignore_errors: yes  # This ensures it won't fail if the group already exists

- name: Add user to docker group
  user:
    name: "{{ ansible_user | default('ubuntu') }}"
    groups: docker
    append: yes
- name: Create Docker group
  command: newgrp docker
  ignore_errors: yes  # This ensures it won't fail if the group already exists
